### PR TITLE
Add more install info to readme

### PR DESCRIPTION
**Pull request by marcospgp**

### CODE REVIEW

**Comment by marcospgp** [comment]
No comment? Kind of rude

**Comment by keijiro** [comment]
@marcospgp I'm very sorry about that. Please understand that reading/writing English text is quite time consuming task for non-English speakers like me. I have to spend lots of time to read/write documentation and this kind of comments. I have over 600 public repositories on GitHub, so time management is crucial for me.

**Comment by designerfuzzi** [comment]
thats not an excuse. 
The platform is not to support a single programmer, the platform is made to support shared projects. Consider integrating man power to maintain your stuff instead. 

I am reading since a while whats up here just to find out its finaly C# in audio terms a completely useless framework.

**Comment by marcospgp** [comment]
It's okay @keijiro , thanks for apologizing, but do you just not accept pull requests? If so please consider mentioning that in the readme so people like me won't assume otherwise 😊

Thank you for your work!

**Comment by keijiro** [comment]
@marcospgp Sometime I accept a pull request, but basically, I'm very careful about it because:

- If it's a code change, there is a security risk.
- If it's a documentation change, I can't access the quality of it due to the lack of the language skills.

Thanks for the advice. It's hard to explain this circumstance in every readme file, but I'll consider it.

**Comment by keijiro** [comment]
@designerfuzzi Thank you for the response. I'm sorry, but I can't understand the second paragraph. I guess that it makes sense to native speakers, but it's not very clear for those who only has limited language skills (auto translators also failed to interpret it). Did you conclude that Lasp is completely useless?

**Pull request closed without merging**
